{% set name = "otter-grader" %}
{% set version = "6.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7dab2ad4876e229209bda333996c631b09a7cbc72246a90f97c6dda3148fd127

build:
  entry_points:
    - otter=otter.cli:cli
    - gmail_oauth2=otter.plugins.builtin.gmail_notifications.bin.gmail_oauth2:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - ipython
    - dill
    - jinja2
    - nbformat
    - pandas
    - pyyaml
    - python-on-whales
    - requests
    - wrapt
    - jupytext
    - click
    - fica >=0.2.0
    - google-api-python-client
    - google-auth-oauthlib
    - six
    - nbconvert-core
    - astunparse
    - ipylab
    - ipywidgets

test:
  imports:
    - otter
  commands:
    - pip check
    - otter --help
    - gmail_oauth2 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ucbds-infra/otter-grader
  summary: Python and Jupyter Notebook autograder
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
