{% set name = "otter-grader" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/otter-grader-{{ version }}.tar.gz
  sha256: fb4cc0d33ae2bb52d207af3ecc216c4c4e588bc718d299da92f7db9eb81a4a95

build:
  entry_points:
    - otter=otter.cli:cli
    - gmail_oauth2=otter.plugins.builtin.gmail_notifications.bin.gmail_oauth2:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ipython
    - dill
    - jinja2
    - nbformat
    - pandas
    - pyyaml
    - python-on-whales
    - requests
    - wrapt
    - jupytext
    - click
    - fica >=0.2.0
    - google-api-python-client
    - google-auth-oauthlib
    - six

test:
  imports:
    - otter
  commands:
    - pip check
    - otter --help
    - gmail_oauth2 --help
  requires:
    - pip

about:
  home: https://github.com/ucbds-infra/otter-grader
  summary: Python and Jupyter Notebook autograder
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
