{% set name = "otter-grader" %}
{% set version = "6.1.6" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 23f67966cb251c0fcdaeeb95a242bdc9fd76cf71c9cdb7e75ba6da763cd97dd7

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}

outputs:
  - name: {{ name|lower }}-base
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
      entry_points:
        - otter=otter.cli:cli
        - gmail_oauth2=otter.plugins.builtin.gmail_notifications.bin.gmail_oauth2:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - poetry
      run:
        - python >={{ python_min }}
        - ipython
        - dill
        - jinja2
        - nbformat
        - pandas
        - pyyaml
        - python-on-whales
        - requests
        - wrapt
        - jupytext
        - click
        - fica >=0.2.0
        - google-api-python-client
        - google-auth-oauthlib
        - six
        - astunparse
        - ipylab
        - ipywidgets
    test:
      imports:
        - otter
  - name: {{ name|lower }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
      entry_points:
        - otter=otter.cli:cli
        - gmail_oauth2=otter.plugins.builtin.gmail_notifications.bin.gmail_oauth2:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - poetry
      run:
        - {{ pin_subpackage("otter-grader-base", exact=True) }}
        - nbconvert-core >=6.0.0
    test:
      imports:
        - otter
      commands:
        - pip check
        - otter --help
        - gmail_oauth2 --help
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/ucbds-infra/otter-grader
  summary: Python and Jupyter Notebook autograder
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
