{% set name = "otter-grader" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1cf10e473519af76da1a21ee39287387fa71e6f4c4daae0a564a7afb8c3ea37

build:
  entry_points:
    - otter=otter.cli:cli
    - gmail_oauth2=otter.plugins.builtin.gmail_notifications.bin.gmail_oauth2:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - ipython
    - dill
    - jinja2
    - nbformat
    - pandas
    - pyyaml
    - python-on-whales
    - requests
    - wrapt
    - jupytext
    - click
    - fica >=0.2.0
    - google-api-python-client
    - google-auth-oauthlib
    - six
    - nbconvert-core
    - astunparse
    - ipylab
    - ipywidgets

test:
  imports:
    - otter
  commands:
    - pip check
    - otter --help
    - gmail_oauth2 --help
  requires:
    - pip

about:
  home: https://github.com/ucbds-infra/otter-grader
  summary: Python and Jupyter Notebook autograder
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
