schema_version: 1

context:
  name: otter-grader
  version: 6.1.6

recipe:
  name: ${{ name|lower }}-split
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 23f67966cb251c0fcdaeeb95a242bdc9fd76cf71c9cdb7e75ba6da763cd97dd7

build:
  number: 2

outputs:
  - package:
      name: ${{ name|lower }}-base
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
      python:
        entry_points:
          - otter=otter.cli:cli
          - gmail_oauth2=otter.plugins.builtin.gmail_notifications.bin.gmail_oauth2:main
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - poetry
      run:
        - python >=${{ python_min }}
        - ipython
        - dill
        - jinja2
        - nbformat
        - pandas
        - pyyaml
        - python-on-whales
        - requests
        - wrapt<2.0.0,>=1.16.0
        - jupytext
        - click
        - fica >=0.2.0
        - google-api-python-client
        - google-auth-oauthlib
        - six
        - astunparse
        - ipylab
        - ipywidgets
    tests:
      - python:
          python_version: ${{ python_min }}.*
          pip_check: false
          imports:
            - otter
      - script:
          - otter --help
          - gmail_oauth2 --help
        requirements:
          run:
            - python ${{ python_min }}.*

  - package:
      name: ${{ name|lower }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name|lower ~ '-base', exact=True) }}
        - nbconvert-core
    tests:
      - python:
          python_version: ${{ python_min }}.*
          pip_check: true
          imports:
            - otter

about:
  summary: Python and Jupyter Notebook autograder
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/ucbds-infra/otter-grader

extra:
  recipe-maintainers:
    - chrispyles
